<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">formatNameForKS8Compatibility</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRD
dXJzb3IoKTsKU3RyaW5nIHZhbHVlID0gSURhdGFVdGlsLmdldFN0cmluZyhwaXBlbGluZUN1cnNv
ciwgInZhbHVlIik7ClN0cmluZyBtYXhMZW4gPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKHBpcGVsaW5l
Q3Vyc29yLCAibWF4TGVuIik7ClN0cmluZyByZXBsYWNlRG90cyA9IElEYXRhVXRpbC5nZXRTdHJp
bmcocGlwZWxpbmVDdXJzb3IsICJyZXBsYWNlRG90cyIpOwoKaW50IG1heCA9IDA7Cgp0cnkgeyBt
YXggPSBJbnRlZ2VyLnBhcnNlSW50KG1heExlbik7IH0gY2F0Y2goRXhjZXB0aW9uIGUpIHt9IC8v
IGRvIG5vdyd0CgppZiAodmFsdWUgIT0gbnVsbCkgewoJdmFsdWUgPSB2YWx1ZS50b0xvd2VyQ2Fz
ZSgpLnJlcGxhY2UoIiAiLCAiLSIpOwoJdmFsdWUgPSB2YWx1ZS5yZXBsYWNlKCJfIiwgIi0iKTsK
CQoJaWYgKG1heCA+IDAgJiYgdmFsdWUubGVuZ3RoKCkgPiBtYXgpCgkJdmFsdWUgPSB2YWx1ZS5z
dWJzdHJpbmcoMCwgbWF4KTsKfQoKaWYgKHJlcGxhY2VEb3RzICE9IG51bGwgJiYgcmVwbGFjZURv
dHMuZXF1YWxzSWdub3JlQ2FzZSgidHJ1ZSIpKSB7Cgl2YWx1ZSA9IHZhbHVlLnJlcGxhY2UoIi4i
LCAiLSIpOwp9CgovLyBwaXBlbGluZSBvdXQKCklEYXRhVXRpbC5wdXQocGlwZWxpbmVDdXJzb3Is
ICJ2YWx1ZSIsIHZhbHVlKTsKcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw==</value>
</Values>
