<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">commitAndPushGitRepo</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwbGVpbmUgaW4KCklEYXRhQ3Vyc29yIGMgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKU3Ry
aW5nIGRpciA9IElEYXRhVXRpbC5nZXRTdHJpbmcoYywgImRpciIpOwpTdHJpbmcgZmlsZXNbXSA9
IElEYXRhVXRpbC5nZXRTdHJpbmdBcnJheShjLCAiZmlsZXMiKTsKU3RyaW5nIG1lc3NhZ2UgPSBJ
RGF0YVV0aWwuZ2V0U3RyaW5nKGMsICJtZXNzYWdlIik7ClN0cmluZyByZW1vdmUgPSBJRGF0YVV0
aWwuZ2V0U3RyaW5nKGMsICJyZW1vdmUiKTsKU3RyaW5nIGdpdFVyaSA9IElEYXRhVXRpbC5nZXRT
dHJpbmcoYywgImdpdFVyaSIpOwpTdHJpbmcgZ2l0VXNlciA9IElEYXRhVXRpbC5nZXRTdHJpbmco
YywgImdpdFVzZXIiKTsKU3RyaW5nIGdpdFBhc3N3b3JkID0gSURhdGFVdGlsLmdldFN0cmluZyhj
LCAiZ2l0UGFzc3dvcmQiKTsKCQkKYy5kZXN0cm95KCk7CgkJCi8vIHByb2Nlc3MKCQkJCQp0cnkg
ewoJCglHaXQgZ2l0ID0gY29tbWl0TG9jYWxSZXBvKG5ldyBGaWxlKGRpciksIGZpbGVzLCBtZXNz
YWdlLCByZW1vdmUgIT0gbnVsbCAmJiAgcmVtb3ZlLmVxdWFsc0lnbm9yZUNhc2UoInRydWUiKSk7
CgoJaWYgKGdpdCAhPSBudWxsKSB7CgkJZ2l0LnB1c2goKS5zZXRDcmVkZW50aWFsc1Byb3ZpZGVy
KG5ldyBVc2VybmFtZVBhc3N3b3JkQ3JlZGVudGlhbHNQcm92aWRlcihnaXRVc2VyLCBnaXRQYXNz
d29yZCkpLmNhbGwoKTsKCX0gZWxzZSB7CgkJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIkNv
dWxkbid0IGVzdGFibGlzaCBsb2NhbCByZXBvIGF0ICIgKyBkaXIpOwoJfQp9IGNhdGNoIChFeGNl
cHRpb24gZSkgewoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oZSk7Cn0KCQ==</value>
</Values>
