<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">indexPackages</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgIGluCgpJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvciA9IHBpcGVsaW5lLmdl
dEN1cnNvcigpOwpTdHJpbmcgbmFtZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcocGlwZWxpbmVDdXJz
b3IsICJuYW1lIik7ClN0cmluZyBzb3VyY2VEaXIgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKHBpcGVs
aW5lQ3Vyc29yLCAic291cmNlRGlyZWN0b3J5Iik7CklEYXRhW10gcmVwb3MgPSBJRGF0YVV0aWwu
Z2V0SURhdGFBcnJheShwaXBlbGluZUN1cnNvciwgInJlcG9zaXRvcmllcyIpOwoKLy8gcHJvY2Vz
cwoKUGFja2FnZUludHJvc3BlY3RvciBwID0gUGFja2FnZUludHJvc3BlY3Rvci5kZWZhdWx0SW5z
dGFuY2UobmFtZSwgc291cmNlRGlyLCBjb252ZXJ0VG9NYXAocmVwb3MpLCB0cnVlKTsKCi8vIG91
dHB1dAoKSURhdGFVdGlsLnB1dChwaXBlbGluZUN1cnNvciwgInBhY2thZ2VzIiwgcC5hbGxQYWNr
YWdlcygpKTsKcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOwoJ</value>
</Values>
