<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getNextVersionFromImage</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0
Q3Vyc29yKCk7ClN0cmluZyB0YWcgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKHBpcGVsaW5lQ3Vyc29y
LCAidGFnIik7CmJvb2xlYW4gaXNEZWRpY2F0ZWRSZXBvID0gSURhdGFVdGlsLmdldEJvb2xlYW4o
cGlwZWxpbmVDdXJzb3IsICJpc0RlZGljYXRlZFJlcG8iKTsKCi8vIHByb2Nlc3MKClN0cmluZyB2
ZXJzaW9uID0gIjEuMCI7ClN0cmluZyB0YWdXaXRob3V0VmVyc2lvbiA9ICIiOwppbnQgaW5kZXgg
PSAtMTsKCmlmIChpc0RlZGljYXRlZFJlcG8pIHsKCWluZGV4ID0gdGFnLmxhc3RJbmRleE9mKCI6
Iik7Cn0gZWxzZSB7CglpbmRleCA9IHRhZy5sYXN0SW5kZXhPZigiLSIpOwp9Cgp0YWdXaXRob3V0
VmVyc2lvbiA9IHRhZy5zdWJzdHJpbmcoMCwgaW5kZXgpOwp2ZXJzaW9uID0gdGFnLnN1YnN0cmlu
ZyhpbmRleCsxKTsKCi8vIHBpcGVsaW5lIG91dAoKaWYgKGlzRGVkaWNhdGVkUmVwbykgewoJSURh
dGFVdGlsLnB1dChwaXBlbGluZUN1cnNvciwgInRhZ0xhdGVzdCIsIHRhZ1dpdGhvdXRWZXJzaW9u
ICsgIjpsYXRlc3QiKTsKfSBlbHNlIHsKCUlEYXRhVXRpbC5wdXQocGlwZWxpbmVDdXJzb3IsICJ0
YWdMYXRlc3QiLCB0YWdXaXRob3V0VmVyc2lvbiArICItbGF0ZXN0Iik7Cn0KCklEYXRhVXRpbC5w
dXQocGlwZWxpbmVDdXJzb3IsICJ2ZXJzaW9uIiwgdmVyc2lvbik7CgpwaXBlbGluZUN1cnNvci5k
ZXN0cm95KCk7</value>
</Values>
