<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">pull</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4gCgpJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvciA9IHBpcGVsaW5lLmdl
dEN1cnNvcigpOwpTdHJpbmcgdGFnID0gSURhdGFVdGlsLmdldFN0cmluZyhwaXBlbGluZUN1cnNv
ciwgInRhZyIpOwpTdHJpbmcgZW1haWwgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKHBpcGVsaW5lQ3Vy
c29yLCAiZG9ja2VyRW1haWwiKTsKU3RyaW5nIHVzZXIgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKHBp
cGVsaW5lQ3Vyc29yLCAiZG9ja2VyVXNlciIpOwpTdHJpbmcgcGFzc3dvcmQgPSBJRGF0YVV0aWwu
Z2V0U3RyaW5nKHBpcGVsaW5lQ3Vyc29yLCAiZG9ja2VyUGFzc3dvcmQiKTsKClN0cmluZyBkb2Nr
ZXJIb3N0ID0gSURhdGFVdGlsLmdldFN0cmluZyhwaXBlbGluZUN1cnNvciwgImRvY2tlckhvc3Qi
KTsKU3RyaW5nIGh0dHBzQ2VydCA9IElEYXRhVXRpbC5nZXRTdHJpbmcocGlwZWxpbmVDdXJzb3Is
ICJodHRwc0NlcnQiKTsKCQkKLy8gcHJvY2VzcwoKSURhdGEgaW1hZ2UgPSBudWxsOwoKdHJ5IHsK
CQkJCglpZiAoZW1haWwgIT0gbnVsbCkKCQlpbWFnZSA9IG5ldyBJbWFnZVJlZ2lzdHJ5KERvY2tl
ckNvbm5lY3Rpb25VdGlsLmNyZWF0ZURvY2tlckNsaWVudChkb2NrZXJIb3N0LCBodHRwc0NlcnQp
LCBlbWFpbCwgdXNlciwgcGFzc3dvcmQpLnB1bGwodGFnKTsKCWVsc2UgCgkJaW1hZ2UgPSBuZXcg
SW1hZ2VSZWdpc3RyeShEb2NrZXJDb25uZWN0aW9uVXRpbC5jcmVhdGVEb2NrZXJDbGllbnQoZG9j
a2VySG9zdCwgaHR0cHNDZXJ0KSkucHVsbCh0YWcpOwoKfSBjYXRjaCAoRG9ja2VyQ2VydGlmaWNh
dGVFeGNlcHRpb24gfCBEb2NrZXJFeGNlcHRpb24gfCBJbnRlcnJ1cHRlZEV4Y2VwdGlvbiBlKSB7
CgllLnByaW50U3RhY2tUcmFjZSgpOwoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oZSk7Cn0K
CklEYXRhVXRpbC5wdXQocGlwZWxpbmVDdXJzb3IsICJpbWFnZSIsIGltYWdlKTsKcGlwZWxpbmVD
dXJzb3IuZGVzdHJveSgpOwoJ</value>
</Values>
