<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">images</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4gCgpJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvciA9IHBpcGVsaW5lLmdl
dEN1cnNvcigpOwpTdHJpbmcgZmlsdGVyID0gSURhdGFVdGlsLmdldFN0cmluZyhwaXBlbGluZUN1
cnNvciwgImZpbHRlciIpOwpTdHJpbmcgZG9ja2VySG9zdCA9IElEYXRhVXRpbC5nZXRTdHJpbmco
cGlwZWxpbmVDdXJzb3IsICJkb2NrZXJIb3N0Iik7ClN0cmluZyBodHRwc0NlcnQgPSBJRGF0YVV0
aWwuZ2V0U3RyaW5nKHBpcGVsaW5lQ3Vyc29yLCAiaHR0cHNDZXJ0Iik7CgovLyBwcm9jZXNzCgpp
ZiAoZmlsdGVyICE9IG51bGwpIHsKCQoJaWYgKGZpbHRlci5lbmRzV2l0aCgiLWxhdGVzdCIpKSB7
CgkJCgkJZmlsdGVyID0gZmlsdGVyLnN1YnN0cmluZygwLCBmaWx0ZXIuaW5kZXhPZigiLWxhdGVz
dCIpKTsKCQkKCX0gZWxzZSBpZiAoZmlsdGVyLmVuZHNXaXRoKCI6bGF0ZXN0IikpIHsKCQkKCQlm
aWx0ZXIgPSBmaWx0ZXIuc3Vic3RyaW5nKDAsIGZpbHRlci5pbmRleE9mKCI6bGF0ZXN0IikpOwoJ
fSBlbHNlIGlmIChmaWx0ZXIuaW5kZXhPZigiOiIpICE9IC0xKSB7CgkJCgkJaW50IGluZGV4ID0g
ZmlsdGVyLmluZGV4T2YoIjoiKTsKCQlTdHJpbmcgYjQgPSBmaWx0ZXIuc3Vic3RyaW5nKDAsIGlu
ZGV4KTsKCQlTdHJpbmcgYWZ0ZXIgPSBmaWx0ZXIuc3Vic3RyaW5nKGluZGV4KzEpOwoJCQoJCWlm
IChJbWFnZVJlZ2lzdHJ5LmlzVmVyc2lvbihhZnRlcikpIHsKCQkJZmlsdGVyID0gYjQ7CgkJfSBl
bHNlIGlmIChhZnRlci5pbmRleE9mKCItIikgIT0gLTEpIHsKCQkJaW50IG5pbmRleCA9IGFmdGVy
LmluZGV4T2YoIi0iKTsKCQkJU3RyaW5nIG5hbWUgPSBhZnRlci5zdWJzdHJpbmcoMCwgbmluZGV4
KTsKCQkJCgkJCWZpbHRlciA9IGI0ICsgIjoiICsgbmFtZTsKCQl9Cgl9IGVsc2UgaWYgKGZpbHRl
ci5pbmRleE9mKCItIikgIT0gLTEpIHsKCQkKCQlpbnQgaW5kZXggPSBmaWx0ZXIuaW5kZXhPZigi
LSIpOwoJCVN0cmluZyBiNCA9IGZpbHRlci5zdWJzdHJpbmcoMCwgaW5kZXgpOwoJCVN0cmluZyBh
ZnRlciA9IGZpbHRlci5zdWJzdHJpbmcoaW5kZXgrMSk7CgkJCgkJaWYgKEltYWdlUmVnaXN0cnku
aXNWZXJzaW9uKGFmdGVyKSkgewoJCQlmaWx0ZXIgPSBiNDsKCQl9Cgl9Cn0KCQkKTGlzdDxJRGF0
YT4gaW1hZ2VzOwp0cnkgewoJaW1hZ2VzID0gbmV3IEltYWdlUmVnaXN0cnkoRG9ja2VyQ29ubmVj
dGlvblV0aWwuY3JlYXRlRG9ja2VyQ2xpZW50KGRvY2tlckhvc3QsIGh0dHBzQ2VydCkpLmltYWdl
cyhmaWx0ZXIsIGZpbHRlciA9PSBudWxsKTsKfSBjYXRjaCAoRG9ja2VyQ2VydGlmaWNhdGVFeGNl
cHRpb24gZSkgewoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oZSk7Cn0KCgovLyBwaXBlbGlu
ZSBvdXQKCklEYXRhVXRpbC5wdXQocGlwZWxpbmVDdXJzb3IsICJpbWFnZXMiLCBpbWFnZXMudG9B
cnJheShuZXcgSURhdGFbaW1hZ2VzLnNpemUoKV0pKTsKcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgp
Ow==</value>
</Values>
