<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">deleteAllOtherFilesFromSource</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0
Q3Vyc29yKCk7ClN0cmluZyBzb3VyY2VEaXIgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKHBpcGVsaW5l
Q3Vyc29yLCAic291cmNlRGlyIik7ClN0cmluZyBwYXRoVG9QYWNrYWdlcyA9IElEYXRhVXRpbC5n
ZXRTdHJpbmcocGlwZWxpbmVDdXJzb3IsICJwYXRoVG9QYWNrYWdlcyIpOwpTdHJpbmcgcGF0aFRv
Q29uZmlnID0gSURhdGFVdGlsLmdldFN0cmluZyhwaXBlbGluZUN1cnNvciwgInBhdGhUb0NvbmZp
ZyIpOwpJRGF0YVtdCWZpbGVzVG9LZWVwID0gSURhdGFVdGlsLmdldElEYXRhQXJyYXkocGlwZWxp
bmVDdXJzb3IsICJmaWxlc1RvS2VlcCIpOwoKLy8gcHJvY2VzcwoKTGlzdDxTdHJpbmc+IGZpbGVz
ID0gbmV3IEFycmF5TGlzdDxTdHJpbmc+KCk7CgkKaWYgKGZpbGVzVG9LZWVwICE9IG51bGwpCnsJ
CQkKCWZvciAoIGludCBpID0gMDsgaSA8IGZpbGVzVG9LZWVwLmxlbmd0aDsgaSsrICkKCXsKCQlJ
RGF0YUN1cnNvciBmaWxlc1RvS2VlcEN1cnNvciA9IGZpbGVzVG9LZWVwW2ldLmdldEN1cnNvcigp
OwoJCVN0cmluZyBuID0gSURhdGFVdGlsLmdldFN0cmluZyhmaWxlc1RvS2VlcEN1cnNvciwgInNv
dXJjZSIpOwoJCVN0cmluZyB0ID0gSURhdGFVdGlsLmdldFN0cmluZyhmaWxlc1RvS2VlcEN1cnNv
ciwgImZpbGVUeXBlIik7CgkJCgkJaWYgKG4gIT0gbnVsbCkgewoJCQkKCQkJaWYgKG4uc3RhcnRz
V2l0aCgiLi8iKSkKCQkJCW4gPSBuLnN1YnN0cmluZygyKTsKCQkJCgkJCVN0cmluZyBmaWxlVG9L
ZWVwOwoJCQkKCQkJaWYgKHQgIT0gbnVsbCAmJiB0LmVxdWFsc0lnbm9yZUNhc2UoImNvbmZpZyIp
KSB7CgkJCQlmaWxlVG9LZWVwID0gbmV3IEZpbGUoc291cmNlRGlyLCBuZXcgRmlsZShwYXRoVG9D
b25maWcsIG5ldyBGaWxlKG4pLmdldE5hbWUoKSkuZ2V0UGF0aCgpKS5nZXRQYXRoKCk7CgoJCQl9
IGVsc2UgewoJCQkJZmlsZVRvS2VlcCA9IG5ldyBGaWxlKHNvdXJjZURpciwgbmV3IEZpbGUocGF0
aFRvUGFja2FnZXMsIG5ldyBGaWxlKG4pLmdldE5hbWUoKSkuZ2V0UGF0aCgpKS5nZXRQYXRoKCk7
CgkJCX0KCQkJCQkJCQkKCQkJZmlsZXMuYWRkKGZpbGVUb0tlZXApOwoJCX0KCQkKCQlmaWxlc1Rv
S2VlcEN1cnNvci5kZXN0cm95KCk7Cgl9Cn0KCQpkZWxldGVGaWxlc0luRGlyKG5ldyBGaWxlKHNv
dXJjZURpciksIGZpbGVzLCB0cnVlKTsKCi8vIHBpcGVsaW5lIG91dAoKcGlwZWxpbmVDdXJzb3Iu
ZGVzdHJveSgpOw==</value>
</Values>
