<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">updateVersionInAPIList</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0
Q3Vyc29yKCk7ClN0cmluZyBhcGlOYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyhwaXBlbGluZUN1
cnNvciwgImFwaU5hbWUiKTsKU3RyaW5nIG5ld1ZlcnNpb24gPSBJRGF0YVV0aWwuZ2V0U3RyaW5n
KHBpcGVsaW5lQ3Vyc29yLCAibmV3VmVyc2lvbiIpOwpTdHJpbmcgYXBpTGlzdCA9IElEYXRhVXRp
bC5nZXRTdHJpbmcocGlwZWxpbmVDdXJzb3IsICJhcGlMaXN0Iik7CgovLyBwcm9jZXNzCgppZiAo
YXBpTGlzdCA9PSBudWxsIHx8IGFwaUxpc3QuZXF1YWxzKCIiKSkKCXJldHVybjsKClN0cmluZ1Rv
a2VuaXplciB0ayA9IG5ldyBTdHJpbmdUb2tlbml6ZXIoYXBpTGlzdCwgIiwiKTsKU3RyaW5nIG91
dCA9IG51bGw7ClN0cmluZyBhcGlOYW1lVHJ1bmMgPSBudWxsOwoKaWYgKGFwaU5hbWUgIT0gbnVs
bCAmJiBhcGlOYW1lLmNvbnRhaW5zKCItIikpIHsKCWFwaU5hbWVUcnVuYyA9IGFwaU5hbWUuc3Vi
c3RyaW5nKDAsIGFwaU5hbWUubGFzdEluZGV4T2YoIi0iKSkudG9Mb3dlckNhc2UoKTsKfQoKd2hp
bGUgKHRrLmhhc01vcmVUb2tlbnMoKSkgewoJU3RyaW5nIGUgPSB0ay5uZXh0VG9rZW4oKTsKCQoJ
aWYgKGUuY29udGFpbnMoIi8iKSkgewoJCWUgPSBlLnN1YnN0cmluZygwLCBlLmluZGV4T2YoIi8i
KSk7Cgl9CgkJCQkKCWlmIChlLnRvTG93ZXJDYXNlKCkuZXF1YWxzKGFwaU5hbWUudG9Mb3dlckNh
c2UoKSkgfHwgKGFwaU5hbWVUcnVuYyAhPSBudWxsICYmIGUudG9Mb3dlckNhc2UoKS5lcXVhbHMo
YXBpTmFtZVRydW5jKSkpIHsJCgkJZSArPSAiLyIgKyBuZXdWZXJzaW9uOwkJCQkKCX0KCQoJaWYg
KG91dCA9PSBudWxsKSB7CgkJb3V0ID0gZTsKCX0gZWxzZSB7CgkJb3V0ICs9ICIsIiArIGU7Cgl9
Cn0KCi8vIHBpcGVsaW5lIG91dAoKSURhdGFVdGlsLnB1dChwaXBlbGluZUN1cnNvciwgImFwaUxp
c3QiLCBvdXQpOwpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7</value>
</Values>
