<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">separateFilenameAndPath</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4gCgpJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvciA9IHBpcGVsaW5lLmdl
dEN1cnNvcigpOwpTdHJpbmcgYmFzZURpciA9IElEYXRhVXRpbC5nZXRTdHJpbmcocGlwZWxpbmVD
dXJzb3IsICJiYXNlRGlyIik7ClN0cmluZyBmaWxlbmFtZSA9IElEYXRhVXRpbC5nZXRTdHJpbmco
cGlwZWxpbmVDdXJzb3IsICJmaWxlbmFtZSIpOwoKLy8gcHJvY2Vzc3MKClN0cmluZyBzZXBhcmF0
b3IgPSBTeXN0ZW0uZ2V0UHJvcGVydHkoImZpbGUuc2VwYXJhdG9yIik7ClN0cmluZyBzcmNEaXIg
PSBiYXNlRGlyOwoKaWYgKHNyY0RpciA9PSBudWxsKSB7CglzcmNEaXIgPSAiLi8iOwp9CgppZiAo
ZmlsZW5hbWUgIT0gbnVsbCAmJiBmaWxlbmFtZS5jb250YWlucyhzZXBhcmF0b3IpKSB7CglGaWxl
IGYgPSBuZXcgRmlsZShmaWxlbmFtZSk7CglzcmNEaXIgPSBuZXcgRmlsZShzcmNEaXIsIGYuZ2V0
UGFyZW50KCkpLmdldFBhdGgoKTsKCWZpbGVuYW1lID0gZi5nZXROYW1lKCk7Cn0KCi8vIHBpcGVs
aW5lIG91dAoKSURhdGFVdGlsLnB1dChwaXBlbGluZUN1cnNvciwgInBhdGgiLCBzcmNEaXIpOwpJ
RGF0YVV0aWwucHV0KHBpcGVsaW5lQ3Vyc29yLCAibmFtZSIsIGZpbGVuYW1lKTsKcGlwZWxpbmVD
dXJzb3IuZGVzdHJveSgpOwoJ</value>
</Values>
