<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">zipIt</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0
Q3Vyc29yKCk7ClN0cmluZyBzb3VyY2VGb2xkZXIgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKHBpcGVs
aW5lQ3Vyc29yLCAic291cmNlRm9sZGVyIik7ClN0cmluZyB6aXBGaWxlID0gSURhdGFVdGlsLmdl
dFN0cmluZyhwaXBlbGluZUN1cnNvciwgInppcEZpbGUiKTsKCi8vIHByb2Nlc3MKClN5c3RlbS5v
dXQucHJpbnRsbigiYnVpbGQgZGlyIGlzICIgKyBzb3VyY2VGb2xkZXIgKyAiLCBwcmVwYXJpbmcg
emlwIGZpbGUgIiArIHppcEZpbGUpOwoKdHJ5IHsKCWlmICghemlwRmlsZS5zdGFydHNXaXRoKCIv
IikgJiYgIXppcEZpbGUuc3RhcnRzV2l0aCgiLi8iKSkKCQl6aXBGaWxlID0gbmV3IEZpbGUobmV3
IEZpbGUoc291cmNlRm9sZGVyKS5nZXRQYXJlbnQoKSwgemlwRmlsZSkuZ2V0QWJzb2x1dGVQYXRo
KCk7CgoJaWYgKCF6aXBGaWxlLmVuZHNXaXRoKCIuemlwIikpCgkJemlwRmlsZSArPSAiLnppcCI7
CgoJbmV3IFppcHBlcigpLnppcEl0KHNvdXJjZUZvbGRlciwgemlwRmlsZSk7CgoJYnl0ZVtdIGNv
bnRlbnRzOwoKCWNvbnRlbnRzID0gRmlsZXMucmVhZEFsbEJ5dGVzKEZpbGVTeXN0ZW1zLmdldERl
ZmF1bHQoKS5nZXRQYXRoKHppcEZpbGUpKTsKfSBjYXRjaCAoSU9FeGNlcHRpb24gZSkgewoJZS5w
cmludFN0YWNrVHJhY2UoKTsKCQoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIkNhbm5vdCBy
ZWFkIHppcHBlZCBmaWxlICciICsgemlwRmlsZSArICInICIgKyBlLmdldExvY2FsaXplZE1lc3Nh
Z2UoKSk7Cn0KCi8vIHBpcGVsaW5lIG91dAoKLy9JRGF0YVV0aWwucHV0KHBpcGVsaW5lQ3Vyc29y
LCAiY29udGVudHMiLCBjb250ZW50cyk7CgppZiAoemlwRmlsZSAhPSBudWxsKQoJSURhdGFVdGls
LnB1dChwaXBlbGluZUN1cnNvciwgInppcEZpbGUiLCBuZXcgRmlsZSh6aXBGaWxlKS5nZXROYW1l
KCkpOwoKcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw==</value>
</Values>
