<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">replaceServerAddress</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0
Q3Vyc29yKCk7ClN0cmluZyBob3N0ID0gSURhdGFVdGlsLmdldFN0cmluZyhwaXBlbGluZUN1cnNv
ciwgImhvc3QiKTsKU3RyaW5nIHBvcnQgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKHBpcGVsaW5lQ3Vy
c29yLCAicG9ydCIpOwpTdHJpbmcgdXJsID0gSURhdGFVdGlsLmdldFN0cmluZyhwaXBlbGluZUN1
cnNvciwgInVybCIpOwoKaWYgKGhvc3QgIT0gbnVsbCkgewoJCglpbnQgc3RhcnQgPSB1cmwuaW5k
ZXhPZigiLy8iKTsKCVN0cmluZyByZW1haW4gPSB1cmwuc3Vic3RyaW5nKHN0YXJ0KzIpOwoJaW50
IGVuZCA9IHJlbWFpbi5pbmRleE9mKCIvIik7CgkKCWlmIChob3N0LmluZGV4T2YoIjoiKSAhPSAt
MSkgewoJCWhvc3QgPSBob3N0LnN1YnN0cmluZygwLCBob3N0LmluZGV4T2YoIjoiKSk7Cgl9CgkK
CWlmIChwb3J0ICE9IG51bGwpIHsKCQkKCQl1cmwgPSB1cmwuc3Vic3RyaW5nKDAsIHN0YXJ0KSAr
ICIvLyIgKyBob3N0ICsgIjoiICsgcG9ydCArIHJlbWFpbi5zdWJzdHJpbmcoZW5kKTsKCgl9IGVs
c2UgewoJCQoJCWVuZCA9IHJlbWFpbi5pbmRleE9mKCI6Iik7CgkJdXJsID0gdXJsLnN1YnN0cmlu
ZygwLCBzdGFydCkgKyAiLy8iICsgaG9zdCArIHJlbWFpbi5zdWJzdHJpbmcoZW5kKTsKCX0KfQoK
Ly8gcGlwZWxpbmUgb3V0CgpJRGF0YVV0aWwucHV0KHBpcGVsaW5lQ3Vyc29yLCAidXJsIiwgdXJs
KTsKcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw==</value>
</Values>
